name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        # Explicitly install tools to ensure they're available
        pip install black ruff mypy pytest pytest-cov
        # Debug path
        echo "PATH=$PATH"
        which python
        which pip
        pip list
    
    - name: Check formatting (black)
      run: |
        python -m black --check .
        
    - name: Check linting (ruff)
      run: |
        python -m ruff check .
        
    - name: Check type hints (mypy)
      run: |
        python -m mypy simple_agent/ tests/
        
    - name: Run tests with coverage
      run: |
        python -m pytest --cov=simple_agent --cov-fail-under=90