name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install uv
      run: |
        pip install uv
        
    - name: Install dependencies
      run: |
        uv pip install -e .[dev]
    
    - name: Check formatting and style (black and ruff)
      run: |
        uv run black --check .
        uv run ruff check .
        
    - name: Check type hints (mypy)
      run: |
        uv run mypy simple_agent/ tests/
        
    - name: Run tests with coverage
      run: |
        uv run pytest --cov=simple_agent --cov-fail-under=90